"""adding user and item table

Revision ID: 8c991bb98816
Revises: 4161d362a501
Create Date: 2024-06-18 16:13:12.440203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c991bb98816'
down_revision: Union[str, None] = '4161d362a501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('model', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_model'), 'items', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_model'), table_name='items')
    op.drop_column('items', 'model')
    # ### end Alembic commands ###
